apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-scc
  name: demo-scc
  namespace: demo-scc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: demo-scc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-scc
    spec:
      containers:
      - image: quay.io/dbais76/fedora-httpd-ocp:1.0
        imagePullPolicy: IfNotPresent
        name: fedora-httpd-ocp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: demo-scc
      serviceAccountName: demo-scc
      terminationGracePeriodSeconds: 30
