apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: custom-seccomp
spec:
  baseOSExtensionsContainerImage: ""
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,ewogICAgImRlZmF1bHRBY3Rpb24iOiAiU0NNUF9BQ1RfQUxMT1ciLAogICAgImFyY2hpdGVjdHVyZXMiOiBbCiAgICAgICAgIlNDTVBfQVJDSF9YODZfNjQiLAogICAgICAgICJTQ01QX0FSQ0hfWDg2IiwKICAgICAgICAiU0NNUF9BUkNIX1gzMiIKICAgIF0sCiAgICAic3lzY2FsbHMiOiBbCiAgICAgICAgewogICAgICAgICAgICAibmFtZSI6ICJjaG1vZCIsCiAgICAgICAgICAgICJhY3Rpb24iOiAiU0NNUF9BQ1RfRVJSTk8iLAogICAgICAgICAgICAiYXJncyI6IFtdCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJuYW1lIjogIm1rZGlyIiwKICAgICAgICAgICAgImFjdGlvbiI6ICJTQ01QX0FDVF9FUlJOTyIsCiAgICAgICAgICAgICJhcmdzIjogW10KICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgIm5hbWUiOiAiY2hvd24iLAogICAgICAgICAgICAiYWN0aW9uIjogIlNDTVBfQUNUX0VSUk5PIiwKICAgICAgICAgICAgImFyZ3MiOiBbXQogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAibmFtZSI6ICJjaG93bjMyIiwKICAgICAgICAgICAgImFjdGlvbiI6ICJTQ01QX0FDVF9FUlJOTyIsCiAgICAgICAgICAgICJhcmdzIjogW10KICAgICAgICB9LAoJewogICAgICAgICAgICAibmFtZSI6ICJmY2htb2RhdCIsCiAgICAgICAgICAgICJhY3Rpb24iOiAiU0NNUF9BQ1RfRVJSTk8iLAogICAgICAgICAgICAiYXJncyI6IFtdCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJuYW1lIjogImZjaG93bmF0IiwKICAgICAgICAgICAgImFjdGlvbiI6ICJTQ01QX0FDVF9FUlJOTyIsCiAgICAgICAgICAgICJhcmdzIjogW10KICAgICAgICB9CiAgICBdCn0K
        mode: 0644
        filesystem: root
        overwrite: true
        path: /var/lib/kubelet/seccomp/seccomp-custom.json
