apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2024-05-21T05:40:41Z"
  generation: 2
  labels:
    app: my-demo
  name: my-demo
  namespace: ab-mul
  resourceVersion: "110877"
  uid: 331419e4-539a-4e42-9751-dda75f82d7ed
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: tryme
      creationTimestamp: null
      labels:
        app: my-demo
    spec:
      containers:
      - image: registry.access.redhat.com/rhscl/httpd-24-rhel7
        imagePullPolicy: Always
        name: examples-helloworld-v1
        resources:
          requests:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-05-21T05:41:06Z"
    lastUpdateTime: "2024-05-21T05:41:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-05-21T05:40:41Z"
    lastUpdateTime: "2024-05-21T05:42:48Z"
    message: ReplicaSet "my-demo-7c5f7fbcff" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
