apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-taint
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      nodeSelector:
        env: qa
      containers:
      - name: helloworld
        image: quay.io/dbais76/examples-helloworld-v1:latest
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
        

