apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: demo-dep
  name: demo-dep
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: demo-dep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-dep
    spec:
      containers:
      - image: registry.access.redhat.com/rhscl/httpd-24-rhel7
        imagePullPolicy: Always
        name: demo-con
        resources: {}
        securityContext:
          capabilities:
            drop:
            - CHOWN
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: demo-dep
      serviceAccountName: demo-dep
      terminationGracePeriodSeconds: 30
